Cadastro autores
Dreadlooks/pratica-cdc-servlet pull request #1
Opened 2020-02-07 23:39 UTC by Dreadlooks

2020-02-11 00:41 UTC, asouza requested changes
Esse pr vai ser ótimo, mas tende a ser um pouco demorado :). Como você entrou no mundo da meta programação, via reflection, temos muitos pontos de melhoria. Eu vou revisando e sugerindo melhorias em doses homeopáticas, tudo be,?

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/dao/AuthorDao.java
> +		this.conn = new ConnectionFactory().getConnection();
Se você fizer assim, quem vai fechar a conexão?

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/dao/AuthorDao.java
> +		this.conn = new ConnectionFactory().getConnection();
Fica o desafio, tudo bem?

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/dao/AuthorDao.java
> +			e.printStackTrace();
Se der alguma exception, o ponto do código que invoca esse save não vai saber de nada :). Aqui é importante que você deixe vazar a exception, uma RuntimeException por exemplo. Dessa forma o código não vai funcionar de forma errada.

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/dao/AuthorDao.java
> +		} catch (SQLException e) {
Mesma situação do código de cima. Caso aconteça uma exception, você vai retornar uma lista vazia e ninguém e o outro ponto do código que chama não vai saber o que aconteceu.

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/model/Author.java
> +	public Author() {
*Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

O código, pelo que vi, não invoca este construtor.

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/model/AuthorDto.java
> +	private String description;
o resumo é obrigatório :)

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/model/AuthorOutputDto.java
> +	public AuthorOutputDto(Long id, String name, String description) {
Para as classes de saída, você pode sempre receber como argumento o objeto de domínio, no caso o Autor. E aí você constrói as informações em função do argumento. Se receber tudo separado permite que sejam passadas informações que não necessariamente são de um autor e também dificulta a construção do objeto.

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/servlet/AuthorAddServlet.java
> +		uniqueAuthorNameValidator.checkUniqueKey(authorDto.getName());
Gostei aqui, dividiu e fez todo sentido. Realmente são fluxos de validação distintos. Por outro lado, você quer que esse problema de validação do nome único, entre como erro de validação da request. Como você pode fazeR?

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/servlet/AuthorAddServlet.java
> +		if (validatorsUtil.hasErrors() || uniqueAuthorNameValidator.isInvalid()) {
seria legal você conseguir apenas o hasErrors() aqui :). #desafio

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/servlet/AuthorAddServlet.java
> +			request.setAttribute("errors", validatorsUtil.getErrors());
e apenas o errors aqui :)

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/servlet/AuthorAddServlet.java
> +			RequestDispatcher rd = request.getRequestDispatcher("/WEB-INF/author/new-form.jsp");
que tal chamar o doGet aqui?

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/servlet/UniqueAuthorNameValidator.java
> +			setInvalid(true);
o método privado gera uma indireção aqui para uma lógica simples... podia mandar um this.isInvalid = true direto :)

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/shared/RequestProcessor.java
> +					if (field.getType().isAssignableFrom(String.class)) {
pq esse if/else? dado que o código para o if e else são iguais.

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/shared/RequestProcessor.java
> +		Set<Method> setters = Arrays.asList(dtoClazz.getMethods()).stream().filter(m -> m.getName().startsWith("set"))
belo nome de variável!

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/shared/RequestProcessor.java
> +		Set<Method> setters = Arrays.asList(dtoClazz.getMethods()).stream().filter(m -> m.getName().startsWith("set"))
faz o que uma variável deveria fazer, dar contexto. Ainda mais para um código complicado como esse :)

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/shared/RequestProcessor.java
> +						Method method = dtoClazz.getDeclaredMethod(methodName, String.class);
E se o tipo do argumento for double? Ou estamos esperando aparecer um double? Se for isso eu vou adorar.

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/shared/RequestProcessor.java
> +			return clazz.getDeclaredConstructor().newInstance();
Essa é legal pq é por isso que você de vez em quando precisa de um construtor sem argumentos na sua classe.

2020-02-11 00:41 UTC, asouza commented on src/br/com/caelum/cdc/shared/validators/ValidatorsUtil.java
> +			if (field.isAnnotationPresent(Size.class)) {
Aqui vamos precisar resolver o lance de lidar com outras validações, como @NotBlank etc. O melhor jeito de você generalizar isso é deixar a informação da classe que executa o código de validação perto da annotation. #dica1

2020-02-11 19:01 UTC, Dreadlooks commented on src/br/com/caelum/cdc/model/Author.java
> +	public Author() {
É que como comecei validando ele no meu Validator, eu tinha criado um construtor vazio porque tem uma hora lá que eu invocaria este, mas agora realmente não esta mais sendo utilizado!

2020-02-14 16:29 UTC, Dreadlooks commented on src/br/com/caelum/cdc/shared/RequestProcessor.java
> +					if (field.getType().isAssignableFrom(String.class)) {
Esse não tinha mudado ainda

2020-02-18 22:50 UTC, asouza requested changes
Ficou bem legal! É um código complicado mesmo!

2020-02-18 22:50 UTC, asouza commented on src/br/com/caelum/cdc/dao/AuthorDao.java
> +	public AuthorDao(Connection connection) {
show! isso é o que chamam de injeção de dependências :). Agora você recebe suas dependências prontas e não precisa saber quem cria.

2020-02-18 22:50 UTC, asouza commented on src/br/com/caelum/cdc/model/Author.java
> +	public void setId(Long id) {
pq tem um setId?

2020-02-18 22:50 UTC, asouza commented on src/br/com/caelum/cdc/servlet/AuthorAddServlet.java
> +		BindingResult result = (ConcreteBindingResult) request.getAttribute("bindingResult");
segura esse spring da massa! E realmente não teria outro jeito de buscar esses objetos se não fosse dentro do doPost mesmo. Inclusive que a Servlet é uma instância única... quando for criar atributos, eles não podem específicos de um usuário ou algo assim.

2020-02-18 22:50 UTC, asouza commented on src/br/com/caelum/cdc/servlet/AuthorAddServlet.java
> +		ValidatorsUtil validatorsUtil = new ValidatorsUtil(result);
Esse seu result é justamente o tema de não mexer nos objetos alheios do vídeo de segunda :P. O legal é que você já espera que ele possa ser alterado dentro dos métodos, então está tudo bem :).

2020-02-18 22:50 UTC, asouza commented on src/br/com/caelum/cdc/shared/RequestProcessor.java
>  					if (field.getType().isAssignableFrom(String.class)) {
aqui você poderia ter um mapa meio fixo que associada tipo e converter :).

2020-02-18 22:50 UTC, asouza commented on src/br/com/caelum/cdc/shared/errors/BindingResult.java
> +public interface BindingResult extends Errors {
Legal a inspiração no spring aqui :).

2020-02-18 22:50 UTC, asouza commented on src/br/com/caelum/cdc/shared/filters/BindingResultFilter.java
> +		BindingResult result = (BindingResult) new ConcreteBindingResult();
Aqui não precisa deste cast. ConcreteBindingResult já é um BindingResult

2020-02-18 22:50 UTC, asouza commented on src/br/com/caelum/cdc/shared/validators/UniqueAuthorNameValidationFilter.java
> +		System.out.println(connection);
sobrou sysouts :)

2020-02-18 22:50 UTC, asouza commented on src/br/com/caelum/cdc/shared/validators/ValidatorsUtil.java
> +						result.removeError(field.getName());
pq você da remove aqui?

2020-02-18 22:50 UTC, asouza commented on src/br/com/caelum/cdc/shared/validators/UniqueAuthorNameValidationFilter.java
> +public class UniqueAuthorNameValidationFilter implements Filter {
Pq tem esse filtro?

2020-02-20 16:59 UTC, Dreadlooks commented on src/br/com/caelum/cdc/shared/validators/UniqueAuthorNameValidationFilter.java
> +public class UniqueAuthorNameValidationFilter implements Filter {
Esse eu criei para testar, para ver se seria uma boa, mas aprendi coisas legais com isso, eu ia criar tipo um @Valid para ele poder validar meus campos antes de entrar no método.

2020-02-20 17:33 UTC, Dreadlooks commented on src/br/com/caelum/cdc/shared/validators/ValidatorsUtil.java
> +						result.removeError(field.getName());
Aqui é que antes de acordo com a logica que eu tinha feito, eu precisava remover os erros. Mas agora está tudo certo sem ele, vou tirar.

2020-02-20 17:34 UTC, Dreadlooks commented on src/br/com/caelum/cdc/shared/validators/ValidatorsUtil.java
> +						result.removeError(field.getName());
Acabei deixando passar.

2020-02-20 17:34 UTC, Dreadlooks commented on src/br/com/caelum/cdc/shared/validators/UniqueAuthorNameValidationFilter.java
> +		System.out.println(connection);
Opssss....

2020-02-20 17:35 UTC, Dreadlooks commented on src/br/com/caelum/cdc/shared/filters/BindingResultFilter.java
> +		BindingResult result = (BindingResult) new ConcreteBindingResult();
Ui que vacilo, não sei porque fiz isso

2020-02-20 17:36 UTC, Dreadlooks commented on src/br/com/caelum/cdc/model/Author.java
> +	public void setId(Long id) {
Ah, no DAO quando eu encontro um, eu defino esse id lá para devolver o Autor.

2020-02-20 19:13 UTC, asouza commented on src/br/com/caelum/cdc/model/Author.java
> +	public void setId(Long id) {
Boa! Faz todo sentido!

2020-02-26 23:06 UTC, asouza approved these changes

2020-02-27 15:02 UTC, merged